server.port: 8082

spring:
  application:
    name: backend
     
  resources:
    chain:
      enabled: true
      
security:
  basic:
    enabled: false      
    
jwt:
  secret: trdFmDVIKGhC8wR7be36Jyve3lqQRLTI
  requireAudience: ${spring.application.name} # Enforce token contains 'aud' claim equal to this application's name 
    