server.port: 8083

spring:
  application:
    name: resource
     
  resources:
    chain:
      enabled: true
      
security:
  basic:
    enabled: false      
    
jwt:
  secret: trdFmDVIKGhC8wR7be36Jyve3lqQRLTI
    